package com.example;

import javax.persistence.ElementCollection;

import com.fasterxml.jackson.annotation.JsonIgnore;

import org.drools.persistence.jpa.marshaller.VariableEntity;
import org.kie.dmn.feel.lang.FEELProperty;
import org.kie.dmn.feel.lang.FEELType;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@FEELType
public class ProposalInfo extends VariableEntity {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("order id")
	private long orderId;
	@org.kie.api.definition.type.Label("item name")
	private java.lang.String item;
	@org.kie.api.definition.type.Label("category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("urgency")
	private java.lang.String urgency;

	@org.kie.api.definition.type.Label("premium")
	private double premium;
	@org.kie.api.definition.type.Label("approved")
	private Boolean managerApproval;
	@org.kie.api.definition.type.Label("rejection reason")
	private String rejectionReason;
	@org.kie.api.definition.type.Description("suppliers list to involve")
	@org.kie.api.definition.type.Label("suppliers list")
	@ElementCollection
	@JsonIgnore
	private java.util.List<java.lang.String> suppliersList;
	@org.kie.api.definition.type.Label("target premium")
	private double targetPremium;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ORDERINFO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ORDERINFO_ID_SEQ", name = "ORDERINFO_ID_GENERATOR")
	private java.lang.Long id;

	public ProposalInfo() {
	}

	public ProposalInfo(java.util.List<java.lang.String> suppliersList,
			double targetPremium, long orderId, java.lang.String item,
			java.lang.String category, java.lang.String urgency, double premium,
			java.lang.Boolean managerApproval, java.lang.String rejectionReason) {
		this.suppliersList = suppliersList;
		this.targetPremium = targetPremium;
		this.orderId = orderId;
		this.item = item;
		this.category = category;
		this.urgency = urgency;
		this.premium = premium;
		this.managerApproval = managerApproval;
		this.rejectionReason = rejectionReason;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */

	@Override
	public String toString() {
		return String
				.format("OrderInfo {category: %s, item: %s, managerApproval: %s, orderId: %s, price: %s, rejectionReason: %s, suppliersList: %s, targetPremium: %s, urgency: %s }",
						category, item, managerApproval, orderId, premium,
						rejectionReason, suppliersList, targetPremium, urgency);
	}

	@FEELProperty("order id")
	public long getOrderId() {
		return orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@FEELProperty("item name")
	public java.lang.String getItem() {
		return item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	@FEELProperty("category")
	public java.lang.String getCategory() {
		return category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	@FEELProperty("urgency")
	public java.lang.String getUrgency() {
		return urgency;
	}

	public void setUrgency(java.lang.String urgency) {
		this.urgency = urgency;
	}

	@FEELProperty("premium")
	public double getPremium() {
		return premium;
	}

	public void setPrice(double premium) {
		this.premium = premium;
	}

	@FEELProperty("manager approval")
	public Boolean getManagerApproval() {
		return managerApproval;
	}

	public void setManagerApproval(Boolean managerApproval) {
		this.managerApproval = managerApproval;
	}

	@FEELProperty("rejection reason")
	public String getRejectionReason() {
		return rejectionReason;
	}

	public void setRejectionReason(String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	@FEELProperty("suppliers list")
	public java.util.List<java.lang.String> getSuppliersList() {
		return this.suppliersList;
	}

	public void setSuppliersList(java.util.List<java.lang.String> suppliersList) {
		this.suppliersList = suppliersList;
	}

	@FEELProperty("target premium")
	public double getTargetPremium() {
		return this.targetPremium;
	}

	public void setTargetPremium(double targetPremium) {
		this.targetPremium = targetPremium;
	}

	@FEELProperty("id")
	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public ProposalInfo(long orderId, java.lang.String item,
			java.lang.String category, java.lang.String urgency, double premium,
			java.lang.Boolean managerApproval,
			java.lang.String rejectionReason,
			java.util.List<java.lang.String> suppliersList, double targetPremium,
			java.lang.Long id) {
		this.orderId = orderId;
		this.item = item;
		this.category = category;
		this.urgency = urgency;
		this.premium = premium;
		this.managerApproval = managerApproval;
		this.rejectionReason = rejectionReason;
		this.suppliersList = suppliersList;
		this.targetPremium = targetPremium;
		this.id = id;
	}

	public void copy(ProposalInfo orderInfo) {
		this.orderId = orderInfo.getOrderId();
		this.item = orderInfo.getItem();
		this.category = orderInfo.getCategory();
		this.urgency = orderInfo.getUrgency();
		this.managerApproval = orderInfo.getManagerApproval();
		this.premium = orderInfo.getPremium();
		this.rejectionReason = orderInfo.getRejectionReason();
		//this.suppliersList = orderInfo.getSuppliersList();
		this.targetPremium = orderInfo.getTargetPremium();
	}
}